name: Frontend Linting
on: [push]
jobs:
  FrontendLinting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./client
      - name: Run linters
        run: yarn run lint
        working-directory: ./client